FROM node:24-slim

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run prisma:generate

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
