ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'partner';

DO $$
BEGIN
  CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "preferences" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "refreshTokenHash" TEXT;

UPDATE "User"
SET "status" = CASE WHEN "isActive" THEN 'ACTIVE'::"UserStatus" ELSE 'INACTIVE'::"UserStatus" END
WHERE "isActive" IS NOT NULL;

ALTER TABLE "User" DROP COLUMN IF EXISTS "isActive";
